config/routes.rb
Rails.application.routes.draw do
  resources :paths
  namespace :api, defaults: {format: 'json'} do
    resources :agricultural_companies
    resources :imagens, only: [:index, :create, :destroy, :update, :show]
    resources :routes, only: [:index, :create, :destroy, :update, :show]
    resources :green_houses, only: [:index, :create, :destroy, :update, :show]
    resources :devices, only: [:index, :create, :destroy, :update, :show]
  end
  
  devise_for :users
  root to: "devices#index"
  resources :app
  resources :routes
  resources :green_houses
  resources :devices
  resources :agricultural_companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: "devices#search" 
  get '/change', to: "routes#change"
  get '/redirect/', to: "devices#redirect"
  get '/devices/:id/routes', to: 'devices#routes'
  get '/devices/:id/routes/:route_ind', to: 'devices#route_ind', as: 'device_route_ind'
  get '/devices/:id/routedate/:searchdate/:route_ind', to: 'devices#searchdate', as: "device_searchdate"
  post '/device/routedates', to: "devices#routesdate", as: "device_routesdate"
  end

app/models/path.rb
class Path < ApplicationRecord
  belongs_to :route
  
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :create ]
  skip_before_action :authenticate_user!, only: [ :create ]

  before_action :set_path, only: %i[ show edit update destroy ]

  # GET /paths or /paths.json
  def index
    @paths = Path.all
  end

  # GET /paths/1 or /paths/1.json
  def show
  end

  # GET /paths/new
  def new
    @path = Path.new
  end

  # GET /paths/1/edit
  def edit
  end

  # POST /paths or /paths.json
  def create
    @path = Path.new(path_params)

    respond_to do |format|
      if @path.save
        format.html { redirect_to @path, notice: "Path was successfully created." }
        format.json { render :show, status: :created, location: @path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paths/1 or /paths/1.json
  def update
    respond_to do |format|
      if @path.update(path_params)
        format.html { redirect_to @path, notice: "Path was successfully updated." }
        format.json { render :show, status: :ok, location: @path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paths/1 or /paths/1.json
  def destroy
    @path.destroy
    respond_to do |format|
      format.html { redirect_to paths_url, notice: "Path was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_path
      @path = Path.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def path_params
      params.require(:path).permit(:lat, :lng, :sensor, :velocity, :route_id)
    end
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/views/paths/_form.html.erb
<%= form_with(model: path) do |form| %>
  <% if path.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(path.errors.count, "error") %> prohibited this path from being saved:</h2>

      <ul>
        <% path.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng %>
  </div>

  <div class="field">
    <%= form.label :sensor %>
    <%= form.check_box :sensor %>
  </div>

  <div class="field">
    <%= form.label :routes_id %>
    <%= form.text_field :routes_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/paths/edit.html.erb
<h1>Editing Path</h1>

<%= render 'form', path: @path %>

<%= link_to 'Show', @path %> |
<%= link_to 'Back', paths_path %>

app/views/paths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paths</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th>Sensor</th>
      <th>Routes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paths.each do |path| %>
      <tr>
        <td><%= path.lat %></td>
        <td><%= path.lng %></td>
        <td><%= path.sensor %></td>
        <td><%= path.routes_id %></td>
        <td><%= link_to 'Show', path %></td>
        <td><%= link_to 'Edit', edit_path_path(path) %></td>
        <td><%= link_to 'Destroy', path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Path', new_path_path %>

app/views/paths/new.html.erb
<h1>New Path</h1>

<%= render 'form', path: @path %>

<%= link_to 'Back', paths_path %>

app/views/paths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @path.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @path.lng %>
</p>

<p>
  <strong>Sensor:</strong>
  <%= @path.sensor %>
</p>

<p>
  <strong>Routes:</strong>
  <%= @path.routes_id %>
</p>

<%= link_to 'Edit', edit_path_path(@path) %> |
<%= link_to 'Back', paths_path %>