config/routes.rb
Rails.application.routes.draw do
  resources :paths
  namespace :api, defaults: {format: 'json'} do
    resources :agricultural_companies
    resources :imagens, only: [:index, :create, :destroy, :update, :show]
    resources :routes, only: [:index, :create, :destroy, :update, :show]
    resources :green_houses, only: [:index, :create, :destroy, :update, :show]
    resources :devices, only: [:index, :create, :destroy, :update, :show]
  end
  
  devise_for :users
  root to: "devices#index"
  resources :app
  resources :routes
  resources :green_houses
  resources :devices
  resources :agricultural_companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: "devices#search" 
  get '/change', to: "routes#change"
  get '/redirect/', to: "devices#redirect"
  get '/devices/:id/routes', to: 'devices#routes'
  get '/devices/:id/routes/:route_ind', to: 'devices#route_ind', as: 'device_route_ind'
  get '/devices/:id/routedate/:searchdate/:route_ind', to: 'devices#searchdate', as: "device_searchdate"
  post '/device/routedates', to: "devices#routesdate", as: "device_routesdate"
  end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :agricultural_company
  has_many :routes
end

app/controllers/api/devices_controller.rb
class Api::DevicesController < ApplicationController
    before_action :set_device, only: [:show, :update, :destroy]

    # GET /devices
    def index
      @devices = Device.all
  
      render json: @devices
    end
  
    # GET /devices/1
    def show
      render json: @device
    end
  
    # POST /devices
    def create
      @device = Device.new(device_params)
  
      if @device.save
        render json: @device, status: :created, location: @device
      else
        render json: @device.errors, status: :unprocessable_entity
      end
    end
  
    # PATCH/PUT /devices/1
    def update
      if @device.update(device_params)
        render json: @device
      else
        render json: @device.errors, status: :unprocessable_entity
      end
    end
  
    # DELETE /devices/1
    def destroy
      @device.destroy
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_device
        @device = Device.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def agricultural_company_params
        params.require(:agricultural_company).permit(:name, :address, :phone, :responsable,:image)
      end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: %i[ show edit update destroy routes route_ind searchdate ]

  # GET /devices or /devices.json
  def index
    @devices = current_user.agricultural_companies.first.devices
    @results = @devices.eager_load(:routes).where("routes.id is not null ")
  end
  #Search
  def search
    @devicess = current_user.agricultural_companies.first.devices
      @parameter = params[:search].downcase
      @results = @devicess.eager_load(:routes).where("lower(name) LIKE :search", search: "%#{@parameter}%").where("routes.id is not null ")
  end
  
  def redirect
    redirect_to :controller => 'routes', :action => 'show' , :id => params[:id]
  end

  def routes
    @routes = @device.routes
  end

  def route_ind
    #p @device.to_json
    @index = params[:route_ind].to_i
    @routes = (@device.routes).order('routes.id DESC')
    @countall = @device.routes.all.count
    @route = @routes[@index]
    render :routes
  end
  # GET /devices/1 or /devices/1.json
  def show
  end 

    #Searchdate
  def searchdate
    @routes = @device
      .routes
      .where('to_char("routes"."routedate", \'DD-MM-YYYY\') = ?', params[:searchdate])
    if @routes.length == 0
      redirect_back(fallback_location: root_path)
      flash[:message] = "No hay recorridos en la fecha seleccionada"
    else
      @index = params[:route_ind].to_i
      @countall = @routes.length
      @route = @routes[@index]
      render :routesdate
    end
  end 

  def routesdate
    if params[:searchdate].blank?
      redirect_back(fallback_location: root_path)
      flash[:message] = "No seleccionó fecha"
    else   
      redirect_to '/devices/'+params[:id]+'/routedate/'+params[:searchdate].gsub!('/','-')+'/0'
    end
  end
  
  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices or /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: "Device was successfully created." }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1 or /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: "Device was successfully updated." }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1 or /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: "Device was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def device_params
      params.require(:device).permit(:name, :capacity, :logicaldelete, :agricultural_company_id)
    end
end

app/helpers/api/devices_helper.rb
module Api::DevicesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: device) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>
      <ul>
        <% device.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nombre del dispositivo"%>
    <%= form.text_field :name, class: "form-control styletipo "%>
  </div>

  <div class="field">
    <%= form.label "Capacidad" %>
    <%= form.text_field :capacity, class: "form-control styletipo "%>
  </div>
  <div class="field">
    <%= form.label :agricultural_company_id %>
    <%= form.text_field :agricultural_company_id ,class: "form-control styletipo "%>
    <%# <%= from.select :agricultural_company_id, options_for_select(rou)%> 
 </div>

  <div class="actions">
    <%= form.submit "Agregar Dispositivo"%>
  </div>
<% end %>


<%# <%= f.select :role, options_for_select([["Teacher", "t"], ["Student", "s"]]) 
select("post", "person_id", Person.all.collect { |p| [ p.name, p.id ] }, { prompt: 'Select Person' }) %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<header class="headerdispositivo"> 
</header>

<body>   
  <h3> Dispositivos </h3>
  <div class="containersearch">
      <%= form_tag(search_path,:method => "get") do %>
         <div class="input-group">
            <%= search_field_tag :search, params[:search], placeholder: "Buscar dispositivo", class: "form-control styletipo " %>
            <div class="intput-group-btn">
            <%= button_tag(type: 'submit', class: "btn-search styletipo", :name => nil) do %>
            Buscar  <i class="fas fa-search"></i>  
            <% end %>
         </div>
      </div>
     <% end %>
   </div>  
   <div class="catologcontainer ">
      <div class="row">
         <% @results.each do |results| %>
            <div class="col-xl-2 col-md-1">
               <div class="card bg-success text-white mb-4">
                  <div class="card-footer d-flex align-items-center justify-content-between">
                  <table >
                     <tr> 
                        <th id="letterth" whi=>Dispositivo </th>
                     </tr>
                     <tr> 
                        <td><%= results.name%></td>
                     </tr>
                  </table>
                     <%= link_to "", device_route_ind_path(results.id,0),class:"small text-white stretched-link"%>
                  </div>
               </div>
            </div> 
         <% end %>
      </div>
   </div>
</body>

app/views/devices/indexoriginal.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Capacity</th>
      <th>Status</th>
      <th>Agricultural companies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= device.capacity %></td>
        <td><%= device.status %></td>
        <td><%= device.agricultural_companies_id %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Devicess</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/routes.html.erb
<%= javascript_pack_tag 'devices', 'data-turbolinks-track': 'reload' %>

  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet"/>
  <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<body> 
  <div class="texthead">     
    <h1 class="headertitle">Recorrido</h1>
    <h1 class="headercompany">Compañia </h1>
  </div>
  <div class="labelsinrow">
    <label id="ldate">Fecha: <%= @route.routedate.strftime("%d/%m/%Y")%> </label>
    <label id="lcubot">Cubot: <%= @device.name %></label>
  </div>
  <br>
  <div class="containerdatepicker">
  <div class="container"> 
      <%= form_tag(device_routesdate_path() ) do %>
       <% flash.each do |type, msg| %>
         <div class="alert alert-info" type='hidden'>
            <%= msg %>
          </div>
          <% end %>
        <div class="row">
            <div class='col-sm-6'>
                <div class="form-group">
                    <input type="hidden" name="id" value="<%= @device.id %>"/>
                    <div class='input-group date'id='datetimepicker1' >
                        <input 
                          type='text'
                          name="searchdate"
                          class="form-control"
                          placeholder='Fecha'>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <br>
                    <%= button_tag(type: 'submit', class: "btn-search styletipo") do %>
                      Buscar
                      <i class="fas fa-search">
                      </i>
                    <% end %>
                </div>
            </div>  
        </div> 
    <% end %>
  </div>
  </div>
  <div class="imgrecorrido">
    <article>
      <%= image_tag(@route.image, id: "recorridoimg") %>  
    </article>
    <div class="containerbtn">
      <%= link_to_if(@countall-1 > @index,"<button id=btnnext>Siguiente</button>".html_safe, device_route_ind_path(@device.id, @index +1))%>
      <%= link_to_if(@index >0,"<button id=btnback>Anterior</button>".html_safe, device_route_ind_path(@device.id, @index -1))%>
    </div> 
  </div>
</body>    
<script type="text/javascript">
    $(document).on("turbolinks:load", function(){ 
        $('#datetimepicker1').datetimepicker({format: 'DD/MM/YYYY'});
    });
</script>

app/views/devices/routesdate.html.erb
<%= javascript_pack_tag 'devices', 'data-turbolinks-track': 'reload' %>

  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet"/>
  <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<body> 
  <div class="texthead">     
    <h1 class="headertitle">Recorrido</h1>
    <h1 class="headercompany">Compañia </h1>
  </div>
  <div class="labelsinrow">
    <label id="ldate">Fecha: <%= @route.routedate.strftime("%d/%m/%Y")%> </label>
    <label id="lcubot">Cubot: <%= @device.name %></label>
  </div>
  <br>
  <div class="containerdatepicker">
  <div class="container"> 
      <%= form_tag(device_routesdate_path() ) do %>
        <% flash.each do |type, msg| %>
         <div class="alert alert-info" type='hidden'>
            <%= msg %>
         </div>
        <% end %>
        <div class="row">
            <div class='col-sm-6'>
                <div class="form-group">
                    <input type="hidden" name="id" value="<%= @device.id %>"/>
                    <div class='input-group date'id='datetimepicker1' >
                        <input 
                          type='text'
                          name="searchdate"
                          class="form-control"
                          placeholder='Fecha'>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <br>
                    <%= button_tag(type: 'submit', class: "btn-search styletipo") do %>
                      Buscar
                      <i class="fas fa-search">
                      </i>
                    <% end %>
                </div>
            </div>  
        </div> 
    <% end %>
  </div>
  </div>
  <div class="imgrecorrido">
    <article>
      <%= image_tag(@route.image, id: "recorridoimg") %>  
    </article>
    <div class="containerbtn">
      <%= link_to_if(@countall-1 > @index,"<button id=btnnext>Siguiente</button>".html_safe, device_searchdate_path(@device.id, params[:searchdate] ,@index +1))%>
      <%= link_to_if(@index >0,"<button id=btnback>Anterior</button>".html_safe, device_searchdate_path(@device.id, params[:searchdate], @index -1))%>
    </div> 
  </div>
</body>    
<script type="text/javascript">
    $(document).on("turbolinks:load", function(){ 
        $('#datetimepicker1').datetimepicker({format: 'DD/MM/YYYY'});
    });
</script>

app/views/devices/search.erb
<header class="headerdispositivo"> 
</header> 
<body>
  <h3>Dispositivos </h3>
  <div class="containersearch">
    <%= form_tag(search_path,:method => "get") do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Buscar dispositivo", class: "form-control" %>
      <div class="intput-group-btn">
        <%= button_tag(type: 'submit', class: "btn-search styletipo", :name => nil) do %> Buscar  <i class="fas fa-search"></i>  
        <% end %>
      </div>
    </div>  
    <% end %>
  
  </div>    
  <div class="catologcontainer"> 
     <div class="row">
         <% @results.each do |results| %>
            <div class="col-xl-2 col-md-1">
               <div class="card bg-success text-white mb-4">
                  <div class="card-footer d-flex align-items-center justify-content-between">
                  <table >
                     <tr> 
                        <th id="letterth" whi=>Dispositivo </th>
                     </tr>
                     <tr> 
                        <td><%= results.name%></td>
                     </tr>
                  </table>
                     <%= link_to "", device_route_ind_path(results.id,0),class:"small text-white stretched-link"%>
                  </div>
               </div>
            </div> 
         <% end %>
      </div> 
  </div>   
</body>

app/views/devices/searchdate.html.erb
<%= javascript_pack_tag 'devices', 'data-turbolinks-track': 'reload' %>

<header> 
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet"/>
  <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

  <%= image_tag 'paloverdelogo.png', id: 'pvlogo' %> 
  <h1 class="headertitle">Recorrido</h1>
  <h1 class="headercompany">Compañia</h1>
  <div class="labelsinrow">
    <label id="ldate">Fecha y hora: </label>
    <label id="ldatechange">ldatechange</label>
    <label id="lcubot">Cubot: </label>
  </div>
</header> 
<body>      
  <div class="container"> 
    <%= form_tag(device_routesdate_path(:searchdate)) do %>
        <div class="row">
            <div class='col-sm-6'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker1'>
                        <input type="hidden" name="id" value="<%= @device.id %>"/>
                        <input type='text' name="searchdate" class="form-control" placeholder='Fecha'>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    <br>
                    <%= button_tag(type: 'submit', class: "btn-search styletipo", :searchdate => nil) do %> Buscar  <i class="fas fa-search"></i>
                    <% end %>
                </div>
            </div>  
        </div> 
    <% end %>
  </div>
  <div class="imgrecorrido">
    <article>
      <%= image_tag(@route.image, id: "imgRoute") %>  
    </article>
    <div class="containerbtn">
      <%= link_to_if(@countall-1 > @index,"<button id=btnnext>Siguiente</button>".html_safe, device_route_ind_path(@device.id, @index +1))%>
      <%= link_to_if(@index >0,"<button id=btnback>Anterior</button>".html_safe, device_route_ind_path(@device.id, @index -1))%>
    </div> 
  </div>
</body>    
<script type="text/javascript">
    $(document).on("turbolinks:load", function(){ 
        $('#datetimepicker1').datetimepicker({format: 'DD/MM/YYYY'});
    });
</script>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @device.capacity %>
</p>

<p>
  <strong>Agricultural companies:</strong>
  <%= @device.agricultural_company_id %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>