config/routes.rb
Rails.application.routes.draw do
  resources :paths
  namespace :api, defaults: {format: 'json'} do
    resources :agricultural_companies
    resources :imagens, only: [:index, :create, :destroy, :update, :show]
    resources :routes, only: [:index, :create, :destroy, :update, :show]
    resources :green_houses, only: [:index, :create, :destroy, :update, :show]
    resources :devices, only: [:index, :create, :destroy, :update, :show]
  end
  
  devise_for :users
  root to: "devices#index"
  resources :app
  resources :routes
  resources :green_houses
  resources :devices
  resources :agricultural_companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: "devices#search" 
  get '/change', to: "routes#change"
  get '/redirect/', to: "devices#redirect"
  get '/devices/:id/routes', to: 'devices#routes'
  get '/devices/:id/routes/:route_ind', to: 'devices#route_ind', as: 'device_route_ind'
  get '/devices/:id/routedate/:searchdate/:route_ind', to: 'devices#searchdate', as: "device_searchdate"
  post '/device/routedates', to: "devices#routesdate", as: "device_routesdate"
  end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :device
  has_one_attached :image
  has_many :paths
  accepts_nested_attributes_for :paths
end

app/controllers/api/routes_controller.rb
class Api::RoutesController < ApplicationController
        before_action :set_route, only: [:show, :update, :destroy]
      
        # GET /routes
        def index
          @routes = Route.all
      
          render json: @routes
        end
      
        # GET /routes/1
        def show
          render json: @route
        end
      
        # POST /routes
        def create
          @route = Route.new(route_params)
      
          if @route.save
            render json: @route, status: :created, location: @route
          else
            render json: @route.errors, status: :unprocessable_entity
          end
        end
      
        # PATCH/PUT /routes/1
        def update
          if @route.update(route_params)
            render json: @route
          else
            render json: @route.errors, status: :unprocessable_entity
          end
        end
      
        # DELETE /routes/1
        def destroy
          @route.destroy
        end
      
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_route
            @route = Route.find(params[:id])
          end
      
          # Only allow a list of trusted parameters through.
          def route_params
            params.require(:route).permit(:height, :latitude, :longitud, :devices_id,:image)
          end
      end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :create, :update ]
  skip_before_action :authenticate_user!, only: [ :create, :update ]
  
  before_action :set_route, only: %i[ show edit update destroy ]

  # GET /routes or /routes.json
  def index
    @routes = Route.all
  end



  # GET /routes/1 or /routes/1.json
  def show
  end

  def previous
    Route.where(["id < ?", id]).order(:id).last
  end
  
  def next
    Route.where(["id > ?", id]).order(:id).first
  end


  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end


  # POST /routes or /routes.json
  def create
    device = Device.where(name: params[:route][:device_name]).first
    params[:route].delete :device_name

    @route = Route.new(route_params)
    @route.device = device

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: "Route was successfully created." }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1 or /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: "Route was successfully updated." }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1 or /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: "Route was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def route_params
      params.require(:route).permit(:device_name,:routedate, :image,
        paths_attributes: [:lat, :lng, :sensor, :velocity]
      )
    end
end

app/helpers/api/routes_helper.rb
module Api::RoutesHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_with(model: route, local: true , multipart: true) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
        <% route.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :device_name %>
    <%= form.text_field :device_name   %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/change.html.erb
  <div id="recorrido">
      <header> 
            <%= image_tag 'paloverdelogo.png', id: 'pvlogo' %> 
            <h1 class="headertitle">Recorrido</h1>
            <h1 class="headercompany">Compañia</h1>
            <div class="labelsinrow">
                <label id="lgreenhouse">Invernadero: </label>
                <label id="lgreenhousechange">lgreenhousechange</label>
                <label id="ldate">Fecha y hora: </label>
                <label id="ldatechange">ldatechange</label>
                <label id="lcubotchange">lcubotchange</label>
                <label id="lcubot">Cubot: </label>
              </div>
      </header>
     <body>      
        <div class="imgrecorrido">
         <article>
         <%=image_tag(@route.image)%>

         </article>
          <div class="containerbtn">
            <button id="btnback" ><i class="fas fa-arrow-left "></i> Anterior</button>
            <button id="btnnext"> Siguiente <i class=" fas fa-arrow-right"> </i></button>
         </div> 
      </div>
      </body>    
  </div>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<header >
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet"/>
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.2/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
</header>
<body>    
   <div class="texthead"> 
    <h1 id="headertitle">Recorrido</h1>
    <h1 id="headercompany">Compañia</h1>
    <div class="container"> 
        <!--%= form_tag(routes_routesdate_path(:searchdate)) do %-->
            <div class="row">
                <div class='col-sm-6'>
                    <div class="form-group">
                        <div class='input-group date' id='datetimepicker1'>
                            <input type='text' name="searchdate" class="form-control" placeholder='Fecha'>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                        <br>
                        <%= button_tag(type: 'submit', class: "btn-search styletipo", :searchdate => nil) do %> Buscar  <i class="fas fa-search"></i>
                        <% end %>
                    </div>
                </div>  
            </div> 
        <!--% end %-->
    </div>    
    <div class="labelsinrow">
        <!--label id="lgreenhouse">Invernadero: </label>
        <label id="lgreenhousechange">lgreenhousechange</label-->
        <label id="ldate">Fecha y hora: </label>
        <label id="ldatechange">ldatechange</label>
        <label id="lcubotchange">lcubotchange</label>
        <label id="lcubot">Cubot: </label>
    </div>  
    <div class="imgrecorrido">
        <article>
           <!--%= image_tag (@route.image)%-->
        </article>
        <div class="containerbtn">
            <button id="btnback" ><i class="fas fa-arrow-left "></i> Anterior</button>
            <button id="btnnext"> Siguiente <i class=" fas fa-arrow-right"> </i></button>
        </div> 
    </div> 
</body>
<script type="text/javascript">
    $(document).on("turbolinks:load", function(){ 
        $('#datetimepicker1').datetimepicker({format: 'DD/MM/YYYY'});
    });
</script>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
  <div id="recorrido">
      <header> 
            <%= image_tag 'paloverdelogo.png', id: 'pvlogo' %> 
            <h1 class="headertitle">Recorrido</h1>
            <h1 class="headercompany">Compañia</h1>
            <div class="labelsinrow">
                <label id="ldate">Fecha y hora: </label>
                <label id="ldatechange">ldatechange</label>
                  <label id="lcubot">Cubot: </label>
              </div>
      </header>
     <body>      
        <div class="imgrecorrido">
         <article>
         <%# <%= image_tag(@route.image)%>  

         </article>
          <div class="containerbtn">
            <button id="btnback" ><i class="fas fa-arrow-left "></i> Anterior</button>
            <button id="btnnext"> Siguiente <i class=" fas fa-arrow-right"> </i></button>
         </div> 
      </div>
      </body>    
  </div>