config/routes.rb
Rails.application.routes.draw do
  resources :paths
  namespace :api, defaults: {format: 'json'} do
    resources :agricultural_companies
    resources :imagens, only: [:index, :create, :destroy, :update, :show]
    resources :routes, only: [:index, :create, :destroy, :update, :show]
    resources :green_houses, only: [:index, :create, :destroy, :update, :show]
    resources :devices, only: [:index, :create, :destroy, :update, :show]
  end
  
  devise_for :users
  root to: "devices#index"
  resources :app
  resources :routes
  resources :green_houses
  resources :devices
  resources :agricultural_companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search', to: "devices#search" 
  get '/change', to: "routes#change"
  get '/redirect/', to: "devices#redirect"
  get '/devices/:id/routes', to: 'devices#routes'
  get '/devices/:id/routes/:route_ind', to: 'devices#route_ind', as: 'device_route_ind'
  get '/devices/:id/routedate/:searchdate/:route_ind', to: 'devices#searchdate', as: "device_searchdate"
  post '/device/routedates', to: "devices#routesdate", as: "device_routesdate"
  end

app/models/agricultural_company.rb
class AgriculturalCompany < ApplicationRecord
    has_many :usercompanies
    has_many :users , :through => :usercompanies
    has_many :devices
    has_many :green_houses
end

app/controllers/agricultural_companies_controller.rb
class AgriculturalCompaniesController < ApplicationController
  before_action :set_agricultural_company, only: %i[ show edit update destroy ]

  # GET /agricultural_companies or /agricultural_companies.json
  def index
    @agricultural_companies = AgriculturalCompany.all
  end

  # GET /agricultural_companies/1 or /agricultural_companies/1.json
  def show
    
  end

  # GET /agricultural_companies/new
  def new
    @agricultural_company = AgriculturalCompany.new
  end

  # GET /agricultural_companies/1/edit
  def edit
  end

  # POST /agricultural_companies or /agricultural_companies.json
  def create
    @agricultural_company = AgriculturalCompany.new(agricultural_company_params)

    respond_to do |format|
      if @agricultural_company.save
        format.html { redirect_to @agricultural_company, notice: "Agricultural company was successfully created." }
        format.json { render :show, status: :created, location: @agricultural_company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @agricultural_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agricultural_companies/1 or /agricultural_companies/1.json
  def update
    respond_to do |format|
      if @agricultural_company.update(agricultural_company_params)
        format.html { redirect_to @agricultural_company, notice: "Agricultural company was successfully updated." }
        format.json { render :show, status: :ok, location: @agricultural_company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agricultural_company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agricultural_companies/1 or /agricultural_companies/1.json
  def destroy
    @agricultural_company.destroy
    respond_to do |format|
      format.html { redirect_to agricultural_companies_url, notice: "Agricultural company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agricultural_company
      @agricultural_company = AgriculturalCompany.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agricultural_company_params
      params.require(:agricultural_company).permit(:name, :address, :phone, :responsable)
    end
end

app/controllers/api/agricultural_company_controller.rb
class Api::AgriculturalCompanyController < ApplicationController
    before_action :set_agricultural_company, only: [:show, :update, :destroy]

    # GET /agricultural_companies
    def index
      @agricultural_companies = AgriculturalCompany.all
  
      render json: @agricultural_companies
    end
  
    # GET /agricultural_companies/1
    def show
      render json: @agricultural_company
    end
  
    # POST /agricultural_companies
    def create
      @agricultural_company = AgriculturalCompany.new(agricultural_company_params)
  
      if @agricultural_company.save
        render json: @agricultural_company, status: :created, location: @agricultural_company
      else
        render json: @agricultural_company.errors, status: :unprocessable_entity
      end
    end
  
    # PATCH/PUT /agricultural_companies/1
    def update
      if @agricultural_company.update(agricultural_company_params)
        render json: @agricultural_company
      else
        render json: @agricultural_company.errors, status: :unprocessable_entity
      end
    end
  
    # DELETE /agricultural_companies/1
    def destroy
      @agricultural_company.destroy
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_agricultural_company
        @agricultural_company = AgriculturalCompany.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def agricultural_company_params
        params.require(:agricultural_company).permit(:name, :address, :phone, :responsable)
      end
end

app/helpers/agricultural_companies_helper.rb
module AgriculturalCompaniesHelper
end

app/helpers/api/agricultural_company_helper.rb
module Api::AgriculturalCompanyHelper
end

app/views/agricultural_companies/_form.html.erb
<%= form_with(model: agricultural_company) do |form| %>
  <% if agricultural_company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agricultural_company.errors.count, "error") %> prohibited this agricultural_company from being saved:</h2>

      <ul>
        <% agricultural_company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :responsable %>
    <%= form.text_field :responsable %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agricultural_companies/edit.html.erb
<h1>Editing Agricultural Company</h1>

<%= render 'form', agricultural_company: @agricultural_company %>

<%= link_to 'Show', @agricultural_company %> |
<%= link_to 'Back', agricultural_companies_path %>

app/views/agricultural_companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agricultural Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Responsable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agricultural_companies.each do |agricultural_company| %>
      <tr>
        <td><%= agricultural_company.name %></td>
        <td><%= agricultural_company.address %></td>
        <td><%= agricultural_company.phone %></td>
        <td><%= agricultural_company.responsable %></td>
        <td><%= link_to 'Show', agricultural_company %></td>
        <td><%= link_to 'Edit', edit_agricultural_company_path(agricultural_company) %></td>
        <td><%= link_to 'Destroy', agricultural_company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agricultural Company', new_agricultural_company_path %>

app/views/agricultural_companies/new.html.erb
<h1>New Agricultural Company</h1>

<%= render 'form', agricultural_company: @agricultural_company %>

<%= link_to 'Back', agricultural_companies_path %>

app/views/agricultural_companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agricultural_company.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @agricultural_company.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @agricultural_company.phone %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @agricultural_company.responsable %>
</p>

<%= link_to 'Edit', edit_agricultural_company_path(@agricultural_company) %> |
<%= link_to 'Back', agricultural_companies_path %>